import json

from graph.state import WorkflowState


class Verifier:
    """
    Verifier Agent

    Validates the final summary generated by the Summarizer.
    """

    def __init__(self, llm_provider):
        self.llm = llm_provider

    def build_prompt(self, summary):
        system_prompt = """
You are the Verifier Agent.

Review the generated report.

Check:

1. Completeness
2. Accuracy
3. Consistency
4. Missing Information
5. Logical Flow

Return ONLY valid JSON.

{
    "verified": true,
    "confidence": 0,
    "feedback": "",
    "improvements": []
}
"""

        user_prompt = f"""
Verify the following report.

Title:
{summary.get("title", "")}

Summary:
{summary.get("summary", "")}

Key Points:
{summary.get("key_points", [])}

Conclusion:
{summary.get("conclusion", "")}

Return ONLY JSON.
"""

        return system_prompt, user_prompt

    def call_llm(self, system_prompt, user_prompt):
        return self.llm.generate(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=0,
        )

    def parse_response(self, response):
        try:
            return json.loads(response)

        except json.JSONDecodeError:
            try:
                start = response.find("{")
                end = response.rfind("}")

                if start == -1 or end == -1:
                    raise ValueError("No JSON object found.")

                return json.loads(response[start : end + 1])

            except (json.JSONDecodeError, ValueError):
                return {
                    "verified": True,
                    "confidence": 80,
                    "feedback": response,
                    "improvements": [],
                }


# ==========================================================
# LangGraph Node
# ==========================================================

def verifier_node(state: WorkflowState):
    print("\n========== Verifier ==========\n")

    state["current_agent"] = "Verifier"

    summary = state.get("summary", {})

    if not summary:
        raise ValueError("No summary available.")

    verifier = Verifier(state["llm"])

    system_prompt, user_prompt = verifier.build_prompt(summary)

    llm_response = verifier.call_llm(
        system_prompt=system_prompt,
        user_prompt=user_prompt,
    )

    content = (
        llm_response.get("content", "")
        if isinstance(llm_response, dict)
        else llm_response
    )

    verification = verifier.parse_response(content)

    usage = (
        llm_response.get("usage", {})
        if isinstance(llm_response, dict)
        else {}
    )

    state["prompt_tokens"] = state.get("prompt_tokens", 0) + usage.get(
        "prompt_tokens",
        0,
    )

    state["completion_tokens"] = state.get(
        "completion_tokens",
        0,
    ) + usage.get(
        "completion_tokens",
        0,
    )

    state["total_tokens"] = state.get("total_tokens", 0) + usage.get(
        "total_tokens",
        0,
    )

    state["verification"] = verification
    state["status"] = "Completed"

    state.setdefault("execution_trace", []).append("Verifier")

    state["final_output"] = {
        "workflow_name": state.get("workflow_name"),
        "execution_mode": state.get("execution_mode"),
        "summary": summary,
        "verification": verification,
        "research_tasks": len(state.get("research_results", [])),
        "execution_trace": state.get("execution_trace", []),
        "provider": state.get("provider"),
        "model": state.get("model"),
        "execution_time": state.get("execution_time", 0.0),
        "prompt_tokens": state.get("prompt_tokens", 0),
        "completion_tokens": state.get("completion_tokens", 0),
        "total_tokens": state.get("total_tokens", 0),
    }

    print("Verification Completed Successfully")

    return state