import json

from graph.state import WorkflowState


class Verifier:
    """
    Verifier Agent

    Validates the final summary generated by the Summarizer.
    """

    def __init__(self, llm_provider):
        self.llm = llm_provider

    def build_prompt(self, summary):

        system_prompt = """
You are the Verifier Agent.

Review the generated report.

Check:

1. Completeness
2. Accuracy
3. Consistency
4. Missing Information
5. Logical Flow

Return ONLY valid JSON.

{
    "verified": true,
    "confidence": 0,
    "feedback": "",
    "improvements": []
}
"""

        user_prompt = f"""
Verify the following report.

Title:
{summary.get("title","")}

Summary:
{summary.get("summary","")}

Key Points:
{summary.get("key_points",[])}

Conclusion:
{summary.get("conclusion","")}

Return ONLY JSON.
"""

        return system_prompt, user_prompt

    def call_llm(
        self,
        system_prompt,
        user_prompt,
    ):

        return self.llm.generate(
            system_prompt=system_prompt,
            user_prompt=user_prompt,
            temperature=0,
        )

    def parse_response(self, response):

        try:

            return json.loads(response)

        except Exception:

            try:

                start = response.find("{")
                end = response.rfind("}")

                return json.loads(
                    response[start:end + 1]
                )

            except Exception:

                return {

                    "verified": True,

                    "confidence": 80,

                    "feedback": response,

                    "improvements": []

                }


# ==========================================================
# LangGraph Node
# ==========================================================

def verifier_node(state: WorkflowState):

    print("\n========== Verifier ==========\n")

    state["current_agent"] = "Verifier"

    summary = state.get(
        "summary",
        {}
    )

    if not summary:

        raise Exception(
            "No summary available."
        )

    verifier = Verifier(
        state["llm"]
    )

    system_prompt, user_prompt = verifier.build_prompt(
        summary
    )

    response = verifier.call_llm(
        system_prompt,
        user_prompt,
    )

    verification = verifier.parse_response(
        response
    )

    state["verification"] = verification

    state["final_output"] = {

        "workflow_name": state.get(
            "workflow_name"
        ),

        "execution_mode": state.get(
            "execution_mode"
        ),

        "summary": summary,

        "verification": verification,

        "research_tasks": len(
            state.get(
                "research_results",
                []
            )
        ),

        "execution_trace": state.get(
            "execution_trace",
            []
        )

    }

    state["status"] = "Completed"

    state.setdefault(
        "execution_trace",
        []
    )

    state["execution_trace"].append(
        "Verifier"
    )

    print("Verification Completed Successfully")

    return state