from langgraph.constants import Send

from graph.state import WorkflowState


def route_research_tasks(state: WorkflowState):
    """
    Creates one parallel Research execution
    for every task generated by the Planner.
    """

    tasks = state.get("tasks", [])

    sends = []

    for task in tasks:

        sends.append(

            Send(

                "Research",

                {

                    **state,

                    "current_task": task,

                }

            )

        )

    print(f"\nLaunching {len(sends)} Parallel Research Agents\n")

    return sends